basepath: 'DexYCB'
dataset_name: DexYCB
hand_id: 255

bottle:
    sym: -1
    num_parts: 1

can:
    sym: 1
    num_parts: 1

box:
    sym: 3 
    num_parts: 1

bowl:
    sym: 1
    num_parts: 1
    
banana:
    sym: 4
    num_parts: 1

scissors:
    sym: 4
    num_parts: 1
    
drill:
    sym: 4
    num_parts: 1


